# Week 10
## Pemograman Open Source


operation matrix, append, pop, remove, stacking, resize, reshape, cov, cor regresi OLS
looping for loop 
nested (sorting)

In [1]:
import numpy as np
import pandas as pd

### Stacking, Resize, Reshape

In [2]:
x = np.array([[1,2,3],[5,6,7]])
y = np.array([2,3,4])
z = np.array([7,8,9])
xy = np.vstack((x,y,z))
print(xy)

[[1 2 3]
 [5 6 7]
 [2 3 4]
 [7 8 9]]


In [3]:
a = np.array([[10],[11],[12],[13]])
A = np.hstack((xy,a))
A

array([[ 1,  2,  3, 10],
       [ 5,  6,  7, 11],
       [ 2,  3,  4, 12],
       [ 7,  8,  9, 13]])

In [4]:
np.resize(A, (3,3))

array([[ 1,  2,  3],
       [10,  5,  6],
       [ 7, 11,  2]])

In [5]:
np.resize(A, (2,2))

array([[ 1,  2],
       [ 3, 10]])

In [6]:
np.resize(A, (4,5))

array([[ 1,  2,  3, 10,  5],
       [ 6,  7, 11,  2,  3],
       [ 4, 12,  7,  8,  9],
       [13,  1,  2,  3, 10]])

In [7]:
np.arange(1,13).shape

(12,)

In [8]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
np.arange(1,13,2)

array([ 1,  3,  5,  7,  9, 11])

In [10]:
np.arange(1,13).reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
np.arange(1,13).reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
np.resize(np.arange(1,13),(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Operasi Matrix

In [13]:
mtx1 = np.arange(1,10).reshape((3,3))
mtx1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
mtx2 = np.arange(21,30).reshape((3,3))
mtx2

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [15]:
jumlah  = mtx1 + mtx2
jumlah

array([[22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [16]:
kurang = mtx1 - mtx2;kurang

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [17]:
skalar = mtx1 * mtx2;skalar

array([[ 21,  44,  69],
       [ 96, 125, 156],
       [189, 224, 261]])

In [18]:
perkalian = mtx1 @ mtx2;perkalian

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

In [19]:
perkalian2 = np.dot(mtx1, mtx2);perkalian2

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

In [20]:
np.transpose(perkalian)

array([[150, 366, 582],
       [156, 381, 606],
       [162, 396, 630]])

In [21]:
a = np.array([[10],[11],[12],[13]])
A = np.hstack((np.arange(1,13).reshape((4,3)),a));A

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12],
       [10, 11, 12, 13]])

In [22]:
eigenvalue, eigenvector = np.linalg.eig(A)

In [23]:
eigenvalue

array([ 3.35959179e+01, -5.59591794e+00,  5.53273726e-16, -1.80908797e-15])

In [24]:
eigenvector

array([[-0.28218401, -0.76652284,  0.79021399,  0.44418041],
       [-0.41284944, -0.33089746, -0.50692939,  0.3317623 ],
       [-0.54351488,  0.10472791, -0.3230438 , -0.82113246],
       [-0.67418032,  0.54035329,  0.11927762,  0.13556924]])

In [25]:
det = np.linalg.det(A);det

5.67979851759128e-29

In [26]:
inv = np.linalg.inv(A);inv

array([[-1.00079992e+15,  1.21972490e+15,  5.62949953e+14,
        -7.81874935e+14],
       [ 3.12749974e+14,  9.38249922e+13, -1.12589991e+15,
         7.19324940e+14],
       [ 7.50599938e+14, -1.40737488e+15,  5.62949953e+14,
         9.38249922e+13],
       [-1.87649984e+14,  2.81474977e+14,  0.00000000e+00,
        -9.38249922e+13]])